################################### Default Configuration ############################
baseurl = "https://www.focalmedia.io/"
languageCode = "en"
title = "Stop the Maddness"
theme = "vex-hugo"

#################################### Plugins ##########################################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Droid+Serif:400i|Source+Sans+Pro:300,400,600,700"
  [[params.plugins.css]]
  URL = "https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
  [[params.plugins.css]]
  URL = "css/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "css/themefisher-fonts.css"
  [[params.plugins.css]]
  URL = "css/owl.carousel.css"
  [[params.plugins.css]]
  URL = "css/magnific-popup.css"
  [[params.plugins.css]]
  URL = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/jquery-2.1.1.min.js"
  [[params.plugins.js]]
  URL = "js/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "js/owl.carousel.min.js"
  [[params.plugins.js]]
  URL = "js/jquery.magnific-popup.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.snipcart.com/themes/v3.0.3/default/snipcart.js"


###################################### Navigation ######################################
[menu]
    
  [[menu.main]]
  name = "Gallery"
  URL = "gallery"
  weight = 1

########################### Default parameters ##########################
[params]
logo = ""
home = "Home"
# Meta data
description = "I survived Covid-19 T-Shirt"
author = "stopthemaddness"
# Google Analitycs
google_analitycs_id = "Your ID"
# snipcart public api key
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
# copyright
copyright = "Copyright 2020 &copy; [focalpoint](https://focalmedia.io) | All rights reserved."

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format
